language: haskell

sudo: false

ghc: 8.2

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/codecov-haskell

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack setup
  - cd codecov-haskell
  - cabal sandbox init
  - cabal install codecov-haskell
  - cd ..

script:
  - stack build
  - stack test --coverage

after_script:
  # - codecov-haskell/.cabal-sandbox/bin/codecov-haskell --exclude-dir=test hakocalc-test
