language: haskell

sudo: false

cache:
  directories:
    - $HOME/.cabal

ghc: 8.6.3

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test

after_script:
  - cabal sandbox init
  - cabal install hpc-coveralls --force-reinstalls
  - ./.cabal-sandbox/bin/hpc-coveralls --exclude-dir=test hakocalc-test
