language: haskell

sudo: false

cache:
  directories:
    - $HOME/.stack

  timeout: 300

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - cd $HOME
  - git clone https://github.com/nirum-lang/codecov-haskell -b fix-broken-build-with-retry-0.7
  - cd codecov-haskell
  - stack install
  - cd $TRAVIS_BUILD_DIR

script:
  - stack build
  - stack test --coverage

after_script:
  - $HOME/.local/bin/codecov-haskell --exclude-dir=test hakocalc-test
