language: haskell

ghc: 8.2

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test --show-details=always

after_script:
  - cabal sandbox init
  - cabal install hpc-coveralls
  - ./.cabal-sandbox/bin/hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test hakocalc-test
