language: haskell

sudo: true

ghc: 8.6.3

cache:
  directories:
    - $HOME/.cabal

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal new-build
  - cabal new-test

after_script:
  - mkdir hpc-coveralls
  - cd hpc-coveralls
  - cabal sandbox init
  - cabal new-install hpc-coveralls
  - cd ..
  - hpc-coveralls/.cabal-sandbox/bin/hpc-coveralls --exclude-dir=test hakocalc-test
