language: haskell

sudo: false

cache:
  directories:
    - $HOME/.stack

install:
  - cd $HOME
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack setup
  - git clone https://github.com/guillaume-nargeot/codecov-haskell
  - cd codecov-haskell
  - stack install
  - cd $TRAVIS_BUILD_DIR

script:
  - stack build
  - stack test --coverage

after_script:
  # - codecov-haskell/.cabal-sandbox/bin/codecov-haskell --exclude-dir=test hakocalc-test
