language: haskell

sudo: false

#ghc: 8.6.3

cache:
  directories:
    - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack build
  - stack test --coverage

after_script:
  #- mkdir hpc-coveralls
  #- cd hpc-coveralls
  #- cabal sandbox init
  #- cabal install hpc-coveralls
  #- cd ..
  #- hpc-coveralls/.cabal-sandbox/bin/hpc-coveralls --exclude-dir=test hakocalc-test
