language: haskell

#sudo: required

ghc: 8.4

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test

after_script:
  # - cabal sandbox init
  - cabal install hpc-coveralls
  - hpc-coveralls hakocalc-test
  # - .cabal-sandbox/bin/hpc-coveralls hakocalc-test
