language: haskell

ghc: 8.2

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test

after_script:
  - cabal sandbox init
  - cabal install hpc-coveralls
  - ./.cabal-sandbox/bin/hpc-coveralls --coverage-mode=StrictlyFullLines hakocalc-test
