language: nix

cache:
  directories:
    - $HOME/nix.store
    - $HOME/.stack

  timeout: 600

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo "require-sigs = false" | sudo tee -a /etc/nix/nix.conf > /dev/null

install:
  - curl -sSL https://get.haskellstack.org | sh
  - cd $HOME
  - git clone https://github.com/lunaticare/codecov-haskell
  - cd codecov-haskell
  - stack install
  - cd $TRAVIS_BUILD_DIR

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - stack build
  - stack test --coverage

after_script:
  - export MIX_DIR=$(stack path --dist-dir)/hpc/
  - export TIX_DIR=$(stack path --local-hpc-root)/hakocalc/
  - codecov-haskell hakocalc-test --exclude-dir test --mix-dir $MIX_DIR --tix-dir $TIX_DIR

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs
