language: haskell

#sudo: required

ghc: 8.2

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test

after_script:
  #- cabal sandbox init
  #- cabal install retry-0.5
  #- cabal install cabal-2.0
  #- cabal install codecov-haskell
  - cabal install hpc-coveralls
  #- codecov-haskell hakocalc-test
  #- ./.cabal-sandbox/bin/codecov-haskell hakocalc-test
  - hpc-coveralls hakocalc-test
  # - .cabal-sandbox/bin/hpc-coveralls hakocalc-test
