language: haskell

sudo: false

cache:
  directories:
    - $HOME/masaniwasdp/Hakocalc/.cabal-sandbox

ghc: 8.6.3

before_install:
  - cabal sandbox init

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test

after_script:
  - mkdir hpc-coveralls
  - cd hpc-coveralls
  - cabal sandbox init
  - cabal install hpc-coveralls
  - cd ..
  - hpc-coveralls/.cabal-sandbox/bin/hpc-coveralls --exclude-dir=test hakocalc-test
