language: haskell

sudo: false

cache:
  directories:
    - $HOME/.stack

  timeout: 300

install:
  - export PATH=$HOME/.local/bin:$PATH
  - curl -sSL https://get.haskellstack.org | sh
  - cd $HOME
  - git clone https://github.com/nirum-lang/codecov-haskell -b fix-broken-build-with-retry-0.7
  - cd codecov-haskell
  - stack --verbosity warn install
  - cd $TRAVIS_BUILD_DIR

script:
  - stack --verbosity warn build
  - stack --verbosity warn test --coverage

after_script:
  - find $(stack path --local-hpc-root) -ls
  - codecov-haskell --exclude-dir=test --tix-dir=$(stack path --local-hpc-root)/hakocalc/ hakocalc-test
