language: haskell

sudo: false

#ghc: 8.6.3

cache:
  directories:
    - $HOME/.stack

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack setup

script:
  - stack build
  - stack test --coverage

after_script:
  #- mkdir hpc-coveralls
  #- cd hpc-coveralls
  #- cabal sandbox init
  #- cabal install hpc-coveralls
  #- cd ..
  #- hpc-coveralls/.cabal-sandbox/bin/hpc-coveralls --exclude-dir=test hakocalc-test
