language: minimal

cache:
  directories:
    - $HOME/.stack

  timeout: 600

install:
  - curl -sSL https://get.haskellstack.org | sh
  - cd $HOME
  - git clone https://github.com/8c6794b6/codecov-haskell
  - cd codecov-haskell
  - stack install
  - cd $TRAVIS_BUILD_DIR

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - stack build
  - stack test --coverage

after_script:
  - export MIX_DIR=$(stack path --dist-dir)/hpc/
  - export TIX_DIR=$(stack path --local-hpc-root)/hakocalc/
  - codecov-haskell hakocalc-test --exclude-dir test --mix-dir $MIX_DIR --tix-dir $TIX_DIR
