language: haskell

sudo: required

ghc: 8.4

install:
  #- curl -sSL https://get.haskellstack.org/ | sh
  #- stack setup

script:
  #- stack build
  #- stack test
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

after_script:
  - cabal install codecov-haskell
  - codecov-haskell hakocalc-test