_parserConfigDescA: "Calculates probability that a monster will die, in the Hakoniwa Islands."
_parserConfigDescP: "Calculates probability that a monster will die."
_parserConfigDescQ: "Calculates quantity of missiles to kill a monster."

_parserConfigNameP: "probability"
_parserConfigNameQ: "quantity"

_parserConfigMetaH: "HP"
_parserConfigMetaP: "PROBABILITY"
_parserConfigMetaQ: "MISSILES"

_parserConfigHelpH: "The HP of the monster."
_parserConfigHelpP: "The probability of killing the monster. (%)"
_parserConfigHelpQ: "The quantity of missiles to launch."

_parserConfigCmndC:
  _commandConfigFmtP: "%.3f%%\n"
  _commandConfigFmtQ: "%d\n"
  _commandConfigTxtF: "Could not calculate.\n"